# frozen_string_literal: true

require "bundler/gem_tasks"
<% if use_rspec %>
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)

<% else %>
require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/*_test.rb"]
  t.warning = false
end

<% end %>
begin
  require "rubocop/rake_task"
  RuboCop::RakeTask.new

  RuboCop::RakeTask.new("rubocop:md") do |task|
    task.options << %w[-c .rubocop-md.yml]
  end
rescue LoadError
  task(:rubocop) {}
  task("rubocop:md") {}
end

<% if use_rspec %>
<% if lint_docs %>
task default: %w[rubocop rubocop:md spec]
<% else %>
task default: %w[rubocop spec]
<% end %>
<% else %>
<% if lint_docs %>
task default: %w[rubocop rubocop:md test]
<% else %>
task default: %w[rubocop test]
<% end %>
<% end %>